working kafka

diff --git a/roles/zookeeperset/tasks/main.yml b/roles/zookeeperset/tasks/main.yml
--- a/roles/zookeeperset/tasks/main.yml
+++ b/roles/zookeeperset/tasks/main.yml
@@ -211,6 +211,8 @@
           app: '{{ app }}'   
 
 
+
+          
 - name: Service zookeepersetapp-csvc
   community.kubernetes.k8s:
     definition:
@@ -460,15 +462,13 @@
                     topologyKey: "kubernetes.io/hostname"
             containers:
             - name: cp-kafka-broker
-              image: "confluentinc/cp-kafka:6.2.0"
-              imagePullPolicy: "IfNotPresent"
+              image: "confluentinc/cp-kafka:6.1.0"
+              imagePullPolicy: "Always"
               securityContext:
                 runAsUser: 0
               ports:
               - containerPort: 9092
                 name: kafka
-              - containerPort: 5555
-                name: jmx
               resources:
                 {}
               env:
@@ -491,7 +491,7 @@
               - name: KAFKA_HEAP_OPTS
                 value: -Xms512M -Xmx512M
               - name: KAFKA_ZOOKEEPER_CONNECT
-                value: "zk-hs:2181"
+                value: "zk-cs:2181"
               - name: KAFKA_LOG_DIRS
                 value: "/opt/kafka/data-0/logs"
               - name: KAFKA_METRIC_REPORTERS
@@ -519,14 +519,60 @@
                 export KAFKA_TOOLS_LOG4J_LOGLEVEL=DEBUG && \
                 export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
                 export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_NAME}.kafka-hs.${POD_NAMESPACE}:9092,EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID})) && \
-                exec /etc/confluent/docker/run
+                unset KAFKA_PORT && \
+                echo "KAFKA_ADVERTISED_LISTENERS="$KAFKA_ADVERTISED_LISTENERS &&
+                echo "===> User" && \
+                id && \
+                echo "===> Configuring ..." && \
+                . /etc/confluent/docker/bash-config && \
+                dub ensure KAFKA_ZOOKEEPER_CONNECT  && \
+                dub ensure KAFKA_ADVERTISED_LISTENERS  && \
+                if [[ -z "${KAFKA_LISTENERS-}" ]]; then export KAFKA_LISTENERS &&  KAFKA_LISTENERS=$(cub listeners "$KAFKA_ADVERTISED_LISTENERS") ; fi && \
+                dub path /etc/kafka/ writable  && \
+                if [[ -z "${KAFKA_LOG_DIRS-}" ]]; then export KAFKA_LOG_DIRS && KAFKA_LOG_DIRS="/var/lib/kafka/data"; fi  && \
+                if [[ -n "${KAFKA_ADVERTISED_PORT-}" ]]; then echo "advertised.port is deprecated. Please use KAFKA_ADVERTISED_LISTENERS instead." && exit 1 ; fi  && \
+                if [[ -n "${KAFKA_ADVERTISED_HOST-}" ]]; then echo "advertised.host is deprecated. Please use KAFKA_ADVERTISED_LISTENERS instead." && exit 1 ; fi  && \
+                if [[ -n "${KAFKA_HOST-}" ]];  then echo "host is deprecated. Please use KAFKA_ADVERTISED_LISTENERS instead." && exit 1 ; fi && \
+                if [[ -n "${KAFKA_PORT-}" ]];  then echo ""port is deprecated. Please use KAFKA_ADVERTISED_LISTENERS instead."" && exit 1 ; fi && \
+                # Set if ADVERTISED_LISTENERS has SSL:// or SASL_SSL:// endpoints. && \
+                if [[ $KAFKA_ADVERTISED_LISTENERS == *"SSL://"* ]]; then echo "SSL is enabled." && \
+                  dub ensure KAFKA_SSL_KEYSTORE_FILENAME && \
+                  export KAFKA_SSL_KEYSTORE_LOCATION="/etc/kafka/secrets/$KAFKA_SSL_KEYSTORE_FILENAME"  && \
+                  dub path "$KAFKA_SSL_KEYSTORE_LOCATION" exists  && \
+                  dub ensure KAFKA_SSL_KEY_CREDENTIALS  && \
+                  KAFKA_SSL_KEY_CREDENTIALS_LOCATION="/etc/kafka/secrets/$KAFKA_SSL_KEY_CREDENTIALS" && \
+                  dub path "$KAFKA_SSL_KEY_CREDENTIALS_LOCATION" exists && \
+                  export KAFKA_SSL_KEY_PASSWORD && \
+                  KAFKA_SSL_KEY_PASSWORD=$(cat "$KAFKA_SSL_KEY_CREDENTIALS_LOCATION") && \
+                  dub ensure KAFKA_SSL_KEYSTORE_CREDENTIALS && \
+                  KAFKA_SSL_KEYSTORE_CREDENTIALS_LOCATION="/etc/kafka/secrets/$KAFKA_SSL_KEYSTORE_CREDENTIALS" && \
+                  dub path "$KAFKA_SSL_KEYSTORE_CREDENTIALS_LOCATION" exists && \
+                  export KAFKA_SSL_KEYSTORE_PASSWORD && \
+                  KAFKA_SSL_KEYSTORE_PASSWORD=$(cat "$KAFKA_SSL_KEYSTORE_CREDENTIALS_LOCATION") && \
+                  if [[ -n "${KAFKA_SSL_CLIENT_AUTH-}" ]] && ( [[ $KAFKA_SSL_CLIENT_AUTH == *"required"* ]] || [[ $KAFKA_SSL_CLIENT_AUTH == *"requested"* ]] ) ; then  dub ensure KAFKA_SSL_TRUSTSTORE_FILENAME  && \
+                      export KAFKA_SSL_TRUSTSTORE_LOCATION="/etc/kafka/secrets/$KAFKA_SSL_TRUSTSTORE_FILENAME" && \
+                      dub path "$KAFKA_SSL_TRUSTSTORE_LOCATION" exists && \
+                      dub ensure KAFKA_SSL_TRUSTSTORE_CREDENTIALS && \
+                      KAFKA_SSL_TRUSTSTORE_CREDENTIALS_LOCATION="/etc/kafka/secrets/$KAFKA_SSL_TRUSTSTORE_CREDENTIALS" && \
+                      dub path "$KAFKA_SSL_TRUSTSTORE_CREDENTIALS_LOCATION" exists && \
+                      export KAFKA_SSL_TRUSTSTORE_PASSWORD && \
+                      KAFKA_SSL_TRUSTSTORE_PASSWORD=$(cat "$KAFKA_SSL_TRUSTSTORE_CREDENTIALS_LOCATION") \
+                  ; fi; fi && \
+                # Set if KAFKA_ADVERTISED_LISTENERS has SASL_PLAINTEXT:// or SASL_SSL:// endpoints.  && \
+                if [[ $KAFKA_ADVERTISED_LISTENERS =~ .*SASL_.*://.* ]]; then echo "SASL is enabled" && dub ensure KAFKA_OPTS && if [[ ! $KAFKA_OPTS == *"java.security.auth.login.config"*  ]]; then echo "KAFKA_OPTS should contain 'java.security.auth.login.config' property." ; fi ; fi  && \
+                if [[ -n "${KAFKA_JMX_OPTS-}" ]]; then if [[ ! $KAFKA_JMX_OPTS == *"com.sun.management.jmxremote.rmi.port"*  ]] ; then echo "KAFKA_OPTS should contain 'com.sun.management.jmxremote.rmi.port' property. It is required for accessing the JMX metrics externally." ; fi ; fi  && \
+                dub template "/etc/confluent/docker/${COMPONENT}.properties.template" "/etc/${COMPONENT}/${COMPONENT}.properties" && \
+                dub template "/etc/confluent/docker/log4j.properties.template" "/etc/${COMPONENT}/log4j.properties" && \
+                dub template "/etc/confluent/docker/tools-log4j.properties.template" "/etc/${COMPONENT}/tools-log4j.properties"  && \
+                /etc/confluent/docker/configure  && \
+                echo "Running preflight checks ... " && \
+                /etc/confluent/docker/ensure  && \
+                echo " Launching ... "  && \
+                exec /etc/confluent/docker/launch  
+# exec /etc/confluent/docker/run
               volumeMounts:
                 - name: datadir-0
                   mountPath: /opt/kafka/data-0
-            volumes: 
-            securityContext:
-      #        runAsUser: 1000
-              fsGroup: 0            
         volumeClaimTemplates:
         - metadata:
             name: datadir-0
